### PR TITLE
update kubearmor version to v1.3.2

### PR DESCRIPTION
**Pull request by rksharma95**
*Issue #232 , if available:*

*Description of changes:*
update kubearmor helm chart version to current stable version `v1.3.2`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mikemcd3912** [comment]
Review of the new version is in progress - @rksharma95 while I am working on that can you please update the version tag as well in the namespace file? We are using that in our reporting now to communicate to customers/user which version of the software has been tested across our environments

**Comment by mikemcd3912** [comment]
@rksharma95 In addition to that tag update, we have [updated our functional testing requirements](https://github.com/aws-samples/eks-anywhere-addons?tab=readme-ov-file#functional-job-requirements) since KubeArmor was initially onboarded to require implementation as a cronjob that runs at lease once daily as well as additional testing depth beyond health checks, service endpoint checks or technical checks, so that will need to be updated as well to bring it into compliance with the new requirements. Additional information about those requirements and an example is provided at the link above

**Comment by daemon1024** [comment]
Closes https://github.com/kubearmor/KubeArmor/issues/1698

**Comment by elamaran11** [comment]
@mikemcd3912 Lets get this validated asap.

**Review by mikemcd3912 — APPROVED** [review]
- VMware (K8s 1.28, Bottlerocket 1.15): Pods deploy and reach a ready state, tester completes successfully
- Baremetal (K8s 1.27, Ubuntu 20.04.6 LTS): Pods deploy and reach a ready state, tester completes successfully
- Outposts (K8s 1.27, Amazon Linux 2): Pods deploy and reach a ready state, tester completes successfully
- EKS (K8s 1.28, x86 Amazon Linux 2):  Pods deploy and reach a ready state, tester completes successfully
- EKS (K8s 1.28, x86 Bottlerocket): Pods deploy and reach a ready state, tester completes successfully
- EKS (K8s 1.28, ARM Bottlerocket 1.19): Pods deploy and reach a ready state, tester completes successfully
- EKS (K8s 1.28, ARM Amazon Linux 2): Pods deploy and reach a ready state, tester completes successfully


All environments deploy and test successfully, testing is updated to match requirements and  versioning is added to namespace file to match new update. LGTM

**Pull request merged**
