### PR TITLE
kubecost 2.4.3 bump

### PR DESCRIPTION
**Pull request by jessegoodier**
*Issue #, if available:*

*Description of changes:*
Bump kubecost version from 2.1.0 to 2.4.3

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mikemcd3912** [comment]
Hi, 

The message from Ela was automated, but to add some context it appears a couple of the workloads are experiencing an image pull issue: 

Workloads:
image


Events from the Grafana pod:
image

Events from the Prometheus Pod:
image

**Comment by jessegoodier** [comment]
Thanks @elamaran11 
Will fix and ping back here.

**Comment by elamaran11** [comment]
Looks like your deployment `kubecost-kubecost-grafana` is failing.
Specifically, it looks like these pods are failing: 
* Pod: `kubecost-kubecost-grafana-768f57849c-mn5b8`.
* Pod: `kubecost-kubecost-grafana-768f57849c-mn5b8`.
---- 
Looks like your deployment `kubecost-kubecost-prometheus-server` is failing.
Specifically, it looks like these pods are failing: 
* Pod: `kubecost-kubecost-prometheus-server-c859f75f6-gdx85`.
----

**Comment by jessegoodier** [comment]
2.4.3 should resolve the issues.

**Comment by elamaran11** [comment]
Looks like your deployment `kubecost-kubecost-cost-analyzer` is failing.
Specifically, it looks like these pods are failing: 
* Pod: `kubecost-kubecost-cost-analyzer-6fcb48d6bb-gzh4s`.
----

**Comment by jessegoodier** [comment]
> Looks like your deployment `kubecost-kubecost-cost-analyzer` is failing. Specifically, it looks like these pods are failing:
> 
> * Pod: `kubecost-kubecost-cost-analyzer-6fcb48d6bb-gzh4s`.

Is it possible to re-run the job? if prometheus is not up when cost-analyzer starts, it can restart once or twice.

**Review by mikemcd3912 — APPROVED** [review]
All pods reach a ready state and the testers complete successfully in our environments - LGTM

**Comment by mikemcd3912** [comment]
Thanks for the update @jessegoodier! That last message from Ela was automated but on my manual re-test everything worked great. We appreciate the help getting that working

**Pull request merged**
