### PR TITLE
GitHub actions Update - File structure Edge Cases handling + housekeeping items

### PR DESCRIPTION
**Pull request by mikemcd3912**
*Issue #, if available:*

*Description of changes:*
1. Added logic for handling removal of files 
2. Improved Logic to search for partner namespace file to handle complex file structures, with corresponding update to exit condition for Partner directories not containing a namespace file
3. Removed unnecessary console outputs
4. Updated Close-Pull-Request paths-ignore to match the new PR workflow to avoid errors when Documentation PR's are closed 
5. Added pause to prevent concurrent executions for Re-opened PR's with Synchronization 
6. Improved logic for Synchronized PR handling of Deleted and renamed files

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by elamaran11** [comment]
@mikemcd3912 Nice work, lets review this in our Friday's demo meeting.

**Comment by mikemcd3912** [comment]
@elamaran11 That sounds good, I'll close the PR for now and set the Actions branch targets so that I can demo it in my account for the team on Friday

**Comment by mikemcd3912** [comment]
Updates made for Synch + ReOpen simultaneous GH actions trigger handling

**Review by elamaran11 — APPROVED** [review]
LGTM

**Pull request merged**
