### PR TITLE
Adding Wave Autoscale to the Partners

### PR DESCRIPTION
**Pull request by Ari-suhyeon**
*Description of changes:*
This pull request integrates Wave Autoscale (STCLab) into the AWS EKS testing framework. It includes the following artifacts:

* FluxCD configuration
* External Secret

It needs two keys in Parameter Store. The keys are included in the self-assessment spreadsheet we sent.

* GHRC_TOKEN
* WA_LICENSE

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by elamaran11 — CHANGES_REQUESTED** [review]
Functional Test job is missing. Please check other partner submission for more details. Also please send us your external secrets with full licsense via email.

**Comment by mikemcd3912** [comment]
Thanks for the PR!

I have loaded the secrets you provided into our testing account, however when I went to go test that it was having a little trouble scheduling on our testing environments due to the resource demands. Is the wave-autoscale-autopilot container meant to request 3cpu and 3000Mi memory?

**Comment by Ari-suhyeon** [comment]
Hi @mikemcd3912 

I have identified an issue in the status-check logic within the cronjob.
The logic has been updated to validate the status by checking the response values.
Additionally, I have added a StatefulSet check logic that includes communication with the Kubernetes API.

Please review the changes at your convenience.

**Comment by mikemcd3912** [comment]
Hi @Ari-suhyeon, 

On the functional testing what we're looking for a test of the main function of the solution to show that it is up and running properly, so the health check with the K8s API is still not quite what we are looking for. One example of this is a partner [Tetrate's solution that creates and the subsequently destroys ingress resources](https://github.com/aws-samples/eks-anywhere-addons/blob/main/eks-anywhere-common/Testers/Tetrate.io/tetrate-istiod-testjob-script.yaml) to test the functionality of their product who's function is to manage networking and ingress

Based on my understanding of your solution ideally we'd like to see a test that validates that the intelligent scaling is working as expected, so possibly creating a temporary pod that will be resource constrained from the start then checking whether wave-autoscale performs the necessary autoscaling operation on it before cleaning up the testing resources. 

Let me know if you have any questions or if I can provide additional clarification!

**Comment by Ari-suhyeon** [comment]
Hi @mikemcd3912 ,

I Understood.
To test the auto-scaling functionality, we need to collect metrics, and for this, an agent must be installed as a DaemonSet. I hope this is acceptable to you.
As my schedule does not allow for it this week, I will proceed with the work next week and push the changes accordingly.

**Comment by elamaran11** [comment]
Looks like your deployment `wa-test-dp` is failing.
Specifically, it looks like these pods are failing: 
* Pod: `wa-test-dp-549f5f7f75-2mtcl`.
* Pod: `wa-test-dp-549f5f7f75-6sn6n`.
* Pod: `wa-test-dp-549f5f7f75-6zcw5`.
* Pod: `wa-test-dp-549f5f7f75-c4j8x`.
* Pod: `wa-test-dp-549f5f7f75-cgfn8`.
* Pod: `wa-test-dp-549f5f7f75-f5k85`.
* Pod: `wa-test-dp-549f5f7f75-g78sx`.
* Pod: `wa-test-dp-549f5f7f75-hgmrw`.
* Pod: `wa-test-dp-549f5f7f75-jfrbx`.
* Pod: `wa-test-dp-549f5f7f75-kktgg`.
* Pod: `wa-test-dp-549f5f7f75-ljn4p`.
* Pod: `wa-test-dp-549f5f7f75-mc4dt`.
* Pod: `wa-test-dp-549f5f7f75-mzhf5`.
* Pod: `wa-test-dp-549f5f7f75-prfw6`.
* Pod: `wa-test-dp-549f5f7f75-qrxd9`.
* Pod: `wa-test-dp-549f5f7f75-sswh8`.
* Pod: `wa-test-dp-549f5f7f75-thb79`.
* Pod: `wa-test-dp-549f5f7f75-tzvsc`.
* Pod: `wa-test-dp-549f5f7f75-v4zv6`.
* Pod: `wa-test-dp-549f5f7f75-v7bgn`.
* Pod: `wa-test-dp-549f5f7f75-wsdh2`.
* Pod: `wa-test-dp-549f5f7f75-ww4ld`.
----

**Comment by Ari-suhyeon** [comment]
Hi @elamaran11 
Please let us know what specifically you mean by it failing.
Logs from the cronjob would be great too.
Or are you just saying that the wa-test-dp Deployment failed, not the cronjob?
If so, please provide logs from the pod as well.
Also, did you remove the pv and pvc of the existing wave-autoscale and redeploy it?

**Comment by elamaran11** [comment]
@mikemcd3912 Can you report more details on this error.

**Comment by mikemcd3912** [comment]
Hi @Ari-suhyeon, 

Thanks for the updates! The message about all those failed pods was part of an automation and appear to have been remedied by the redeployment of the solution/volumes after those updates so I'll keep you updated as I complete the rest of the testing. So far our VMware environment test was successful so I believe the current iteration is looking promising

**Comment by elamaran11** [comment]
Looks like your deployment `wa-test-dp` is failing.
Specifically, it looks like these pods are failing: 
* Pod: `wa-test-dp-8ccbc64df-5rxrf`.
----

**Review by mikemcd3912 — APPROVED** [review]
Vmware - Success
Hybrid - Success
Baremetal - Success
Cloud Bottlerocket x86 - Success
Cloud Bottlerocket ARM - Success
Auto Mode - Success

Pods Deploy and testers complete successfully in all environments - LGTM

**Pull request merged**
