### PR TITLE
Update Vault version

### PR DESCRIPTION
**Pull request by gautambaghel**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mikemcd3912** [comment]
Hi @gautambaghel , Thanks for the update PR! 

I'd like to make a request prior to merging - Since Vault was onboarded we have made updates to our [functional testing requirements outlined here](https://github.com/aws-samples/eks-anywhere-addons?tab=readme-ov-file#functional-job-requirements) in which we'll need the tester to be implemented as a CronJob and set up to run once daily so that we can perform ongoing monitoring of the solution's stability and identify any issues quickly if they were to arise.  An example of what we are looking for [can be found here](https://github.com/aws-samples/eks-anywhere-addons/blob/main/eks-anywhere-common/Testers/Komodor/komodor-testjob.yaml) 

The functional tests that are being run look like they're in line with our updated requirements, so all we'll need is that Job converted into a CronJob and have it produce a successful test result across the environments before I can merge the PR

**Comment by gautambaghel** [comment]
Hey @mikemcd3912 - that's fair, I'll track this request however, I won't be able to implement it until later due to other commitments. If you require the PR list to be clean, feel free to close this out I'll open it again.

**Comment by elamaran11** [comment]
@gautambaghel We can currently use the version updates. But please get us a new PR asap for CJ. @mikemcd3912 Lets test and merge this.

**Comment by elamaran11** [comment]
Looks like your deployment `vault-vault-agent-injector` is failing.
Specifically, it looks like these pods are failing: 
* Pod: `vault-vault-agent-injector-74b8b4c8d7-9spxf`.
----

**Comment by gautambaghel** [comment]
@elamaran11 - what is the error exactly? can I get the logs?

**Comment by elamaran11** [comment]
> @elamaran11 - what is the error exactly? can I get the logs?

@gautambaghel Statefulsets are not deploying on Hybrid nodes due to failing readiness probe. @mikemcd3912 Please share the logs from our environment to Gautham

**Review by mikemcd3912 — APPROVED** [review]
Pods deploy and reach a ready state, testers complete successfully - LGTM

**Comment by mikemcd3912** [comment]
@gautambaghel I was able to get my issue figured out on Hybrid Nodes, and the updated version looks good on our other platforms so no action needed! Thanks for checking in to offer troubleshooting assistance

**Pull request merged**
