### PR TITLE
Adding Tetrate Istio Distribution

### PR DESCRIPTION
**Pull request by zirain**
resbumit https://github.com/aws-samples/eks-anywhere-addons/pull/242

### CODE REVIEW

**Review by elamaran11 — COMMENTED** [review]
@zirain Thankyou so much for the PR. @mikemcd3912 @Pjv93 Lets get `tetrate` validated across all EKS-A and EKS deployment models and share feedback of the runs in the PR.

**Comment by mikemcd3912** [comment]
Hi @zirain, 

It looks like we have a collision with another partner's software already using the istio-system namespace that is preventing flux from deploying the tetrate add-on. Please update the namespace to one that will be unique to this add-on so that we can begin testing. For example tetrate-istio could be a good option, but I will leave that naming up to you

Thanks!

**Comment by zirain** [comment]
> Hi @zirain,
> 
> It looks like we have a collision with another partner's software already using the istio-system namespace that is preventing flux from deploying the tetrate add-on. Please update the namespace to one that will be unique to this add-on so that we can begin testing. For example tetrate-istio could be a good option, but I will leave that naming up to you
> 
> Thanks!

Updated

**Comment by elamaran11** [comment]
@mikemcd3912 Can you we get this validated with new `namespace`

**Comment by elamaran11** [comment]
Looks like your deployment `custom-ingressgateway` is failing.
Specifically, it looks like these pods are failing: 
* Pod: `custom-ingressgateway-74f9b8578c-dmvpx`.
----

**Comment by mikemcd3912** [comment]
Hi @zirain , It appears we have success at times but it doesn't seem stable just yet as we encounter an intermittent certificate issue when trying to generate the ingressgateway pod for the tester. I've attached a couple of log files for reference, however all of the failing pods are all experiencing the same issue and output nearly identical logs:

- EKS (K8s 1.28, ARM Bottlerocket 1.19):  Pods deploy and reach a ready state, tester completes successfully on first attempt
- EKS (K8s 1.28, ARM Amazon Linux 2):  Pods deploy and reach a ready state, tester completes successfully on first attempt
- Outposts (K8s 1.27, Amazon Linux 2):  Pods deploy and reach a ready state, tester completes successfully on first attempt
- Snow (K8s 1.28, Ubuntu 20.04.6 LTS ): Pods deploy and reach a ready state, tester completes successfully on first attempt

- VMware (K8s 1.28, Bottlerocket 1.15): Pods deploy and reach a ready state, and while Test succeeds but has a Certificate issue at first in some instances so it doesn't appear consistent. [EKSA VMware failed ingressgateway logs.txt](https://github.com/aws-samples/eks-anywhere-addons/files/15135772/EKSA.VMware.failed.ingressgateway.logs.txt)
- Baremetal (K8s 1.27, Ubuntu 20.04.6 LTS): Pods deploy and reach a ready state, and while Test succeeds but has a Certificate issue at first in some instances so it doesn't appear consistent.  [EKSA Baremetal failed ingressgateway logs.txt](https://github.com/aws-samples/eks-anywhere-addons/files/15135771/EKSA.Baremetal.failed.ingressgateway.logs.txt)
- EKS (K8s 1.28, x86 Amazon Linux 2):  Pods deploy and reach a ready state, and while Test succeeds but has a Certificate issue at first in some instances so it doesn't appear consistent.  [EKS x86 AL2 failed ingressgateway logs.txt](https://github.com/aws-samples/eks-anywhere-addons/files/15135773/EKS.x86.AL2.failed.ingressgateway.logs.txt)
- EKS (K8s 1.28, x86 Bottlerocket):  Pods deploy and reach a ready state, and while Test succeeds but has a Certificate issue at first in some instances so it doesn't appear consistent.  [EKS x86 BR failed ingressgateway logs.txt](https://github.com/aws-samples/eks-anywhere-addons/files/15135770/EKS.x86.BR.failed.ingressgateway.logs.txt)

Let me know if there is anything else I can provide to assist with troubleshooting or if you'd like to set up a time to look at things together live. Thanks!

**Comment by elamaran11** [comment]
Looks like your deployment `custom-ingressgateway` is failing.
Specifically, it looks like these pods are failing: 
* Pod: `custom-ingressgateway-74f9b8578c-rlcqg`.
----

**Comment by mdamt** [comment]
Hi, is there any way we can replicate the testing setup on our end?

**Comment by zirain** [comment]
> Hi, is there any way we can replicate the testing setup on our end?

let's wait https://github.com/aws-samples/eks-anywhere-addons/pull/261 first.

**Comment by elamaran11** [comment]
@zirain #261 Works fine. We wont merge it until we have this PR's functional job working. We want both Istio mesh products to work in Tandem. @mdamt In terms of Local testing please follow the steps [here](https://aws-samples.github.io/eks-anywhere-addons/#pre-requisite-linuxmacos) for test on mac/linux. Alternatively you can use `DevContainers` too for your test and we have built a new functionality for the same which is in PR stage. Check the PR #254 for `DevContainers`.

**Review by mikemcd3912 — APPROVED** [review]
Thank you @zirain  for all of the help troubleshooting this! Everything is working as expected and both istio PR's are co-existing on the clusters with that latest edit applied to Solo. LGTM 

EKSA: 

- VMware (K8s 1.28, Bottlerocket 1.15): Pods deploy and reach a ready state, tester completes successfully on first attempt
- Outposts (K8s 1.27, Amazon Linux 2): Pods deploy and reach a ready state, tester completes successfully on first attempt
- Baremetal (K8s 1.27, Ubuntu 20.04.6 LTS): Pods deploy and reach a ready state, tester completes successfully on first attempt

EKS:

- EKS (K8s 1.28, ARM Bottlerocket 1.19): Pods deploy and reach a ready state, tester completes successfully on first attempt
- EKS (K8s 1.28, ARM Amazon Linux 2): Pods deploy and reach a ready state, tester completes successfully on first attempt
- EKS (K8s 1.28, x86 Amazon Linux 2): Pods deploy and reach a ready state, tester completes successfully on first attempt
- EKS (K8s 1.28, x86 Bottlerocket): Pods deploy and reach a ready state, tester completes successfully on first attempt

**Pull request merged**
