### PR TITLE
Feature/external snapshotter bare metal and vSphere

### PR DESCRIPTION
**Pull request by elamaran11**
*Issue #, if available:*

*Description of changes:*

Storage Drivers with OpenEBs and CSI Snapshotters for BareMetal along with testing process.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by shapirov103 — COMMENTED** [review]
@elamaran11 how many storage classes do we define for baremetal? If jiva is the only class, should not it be marked as default? (currently is set to false)

**Comment by elamaran11** [comment]
> @elamaran11 how many storage classes do we define for baremetal? If jiva is the only class, should not it be marked as default? (currently is set to false)

@shapirov103 This deployment deploys 4 storage classes. Customers can choose between hostpath or Jiva upon their choice as default. I kept it default to false so customers can choose the one they wish. We dont want to force an sc.

**Review by shapirov103 — COMMENTED** [review]
the tester app - does it have to be a pod which stays there all the time? Why not a job?

**Comment by shapirov103** [comment]
> @shapirov103 This deployment deploys 4 storage classes. Customers can choose between hostpath or Jiva upon their choice as default. I kept it default to false so customers can choose the one they wish. We dont want to force an sc.


@elamaran11  This support for storage classes is not a generic approach for EKS-A, but rather is a part of the conformance framework which should work out-of-the-box for partner integrations. We don't want partners to specify a particular storage class when provisioning volumes.
If partner add-on creates a volume without specifying the storage class, what will happen?

**Comment by elamaran11** [comment]
@shapirov103 For vSphere and BareMetal OpenEBS cstor CSI will be our default storage class for our conformance framework.  Customers dont have a need to specify a default storage class in their snippet, it will use CSTOR CSI by default. I have given it as a way to give in example. I have also fixed your Job comment. All good now.

**Review by shapirov103 — APPROVED** [review]
LGTM - great work!

**Pull request merged**
